<a href="https://colab.research.google.com/github/Clinton1029/Loan_Default_Project/blob/main/Loan_Default.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Comparative Analysis of Random Forest and XGBoost Classification Models for Loan Default Prediction

### Final Year Project

**Student:** Clinton Yade  
**Institution:** Dedan Kimathi University of Technology  
**Department:** Mathematics and Physical Sciences  
**Programme:** BSc in Mathematics and Modelling Processes

## 1. Introduction

Loan default prediction is an important application of machine learning in financial risk management.
Financial institutions need reliable methods for identifying borrowers who are likely to default on
their loans.

This project develops and compares two machine learning classification models, Random Forest and
XGBoost, for predicting loan default. The models will be trained using historical borrower and loan
information and evaluated using appropriate classification performance metrics.

## Problem Statement

Loan default is a major challenge for financial institutions, causing financial losses and poor credit risk management. Therefore, reliable machine learning models are needed to accurately predict loan default and support better lending decisions.

## 2. Project Workflow

The project will follow the following steps:

1. Import Required Libraries
2. Load the Dataset
3. Exploratory Data Analysis (EDA)
4. Data Preprocessing and Preparation
5. Feature Selection
6. Split the Dataset into Training and Testing Sets
7. Choose the Machine Learning Models
8. Train the Machine Learning Models
9. Make Predictions
10. Evaluate Model Performance
11. Compare Random Forest and XGBoost
12. Predict Loan Default Outcome for New Borrowers

# 1. Import Required Libraries

The required Python libraries are imported to support data manipulation, data visualization,
data preprocessing, machine learning model development, and model evaluation.

In [3]:
# Import the os library for file and directory operations
import os

# Import pandas for data manipulation and analysis
import pandas as pd

# 2. Load the Dataset

The loan dataset is loaded into the Google Colab environment using Pandas.
The dataset will be used for exploratory data analysis, preprocessing, feature selection,
and development of the machine learning models.

In [4]:

# Define the path to the loan dataset
file_path = "/content/lending_club_loan_two.csv"

# Check if the file exists
if os.path.exists(file_path):
    print("File exists! Loading with pandas...")

    # Load the CSV file into a DataFrame
    df = pd.read_csv(file_path)

    print("\nDataset loaded successfully!")

else:
    print("FILE DOESN'T EXIST")

File exists! Loading with pandas...

Dataset loaded successfully!

# 3. Exploratory Data Analysis (EDA)

Exploratory Data Analysis is performed to understand the structure and characteristics of the loan dataset.
This stage involves examining the dataset dimensions, data types, missing values, duplicate records,
summary statistics, and the distribution of the target variable.

### 3.1 Preview of the Dataset

The first five records of the dataset are displayed to obtain an initial understanding of the available
variables and their values.

In [5]:
# Display the first five rows of the dataset
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,...,16.0,0.0,36369.0,41.8,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,...,17.0,0.0,20131.0,53.3,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,...,13.0,0.0,11987.0,92.2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,...,6.0,0.0,5472.0,21.5,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,...,13.0,0.0,24584.0,69.8,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

### 3.2 Preview of the Last Records

The last five records of the dataset are displayed to verify the end of the dataset and confirm that the data has been loaded correctly.

In [7]:
# Display the last five rows of the dataset
df.tail()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
396025,10000.0,60 months,10.99,217.38,B,B4,licensed bankere,2 years,RENT,40000.0,...,6.0,0.0,1990.0,34.3,23.0,w,INDIVIDUAL,0.0,0.0,"12951 Williams Crossing\r\nJohnnyville, DC 30723"
396026,21000.0,36 months,12.29,700.42,C,C1,Agent,5 years,MORTGAGE,110000.0,...,6.0,0.0,43263.0,95.7,8.0,f,INDIVIDUAL,1.0,0.0,"0114 Fowler Field Suite 028\r\nRachelborough, ..."
396027,5000.0,36 months,9.99,161.32,B,B1,City Carrier,10+ years,RENT,56500.0,...,15.0,0.0,32704.0,66.9,23.0,f,INDIVIDUAL,0.0,0.0,"953 Matthew Points Suite 414\r\nReedfort, NY 7..."
396028,21000.0,60 months,15.31,503.02,C,C2,"Gracon Services, Inc",10+ years,MORTGAGE,64000.0,...,9.0,0.0,15704.0,53.8,20.0,f,INDIVIDUAL,5.0,0.0,"7843 Blake Freeway Apt. 229\r\nNew Michael, FL..."
396029,2000.0,36 months,13.61,67.98,C,C2,Internal Revenue Service,10+ years,RENT,42996.0,...,3.0,0.0,4292.0,91.3,19.0,f,INDIVIDUAL,NaN,0.0,"787 Michelle Causeway\r\nBriannaton, AR 48052"

### 3.3 Dataset Dimensions

The number of rows and columns in the dataset is examined to determine its overall size.

In [6]:
# Display the number of rows and columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 396030
Number of columns: 27

### 3.4 Data Types and Dataset Information

The data types of the variables are examined to identify numerical and categorical features and to
understand the overall structure of the dataset.

In [8]:
# Display information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396030 entries, 0 to 396029
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   loan_amnt             396030 non-null  float64
 1   term                  396030 non-null  object
 2   int_rate              396030 non-null  float64
 3   installment           396030 non-null  float64
 4   grade                 396030 non-null  object
 5   sub_grade             396030 non-null  object
 6   emp_title             373103 non-null  object
 7   emp_length            377729 non-null  object
 8   home_ownership        396030 non-null  object
 9   annual_inc            396030 non-null  float64
 10  verification_status   396030 non-null  object
 11  issue_d               396030 non-null  object
 12  loan_status           396030 non-null  object
 13  purpose               396030 non-null  object
 14  title                 394274 non-null  object
 15  dti                   396030 non-null  float64
 16  earliest_cr_line      396030 non-null  object
 17  open_acc              396030 non-null  float64
 18  pub_rec               396030 non-null  float64
 19  revol_bal             396030 non-null  float64
 20  revol_util            395754 non-null  float64
 21  total_acc             396030 non-null  float64
 22  initial_list_status   396030 non-null  object
 23  application_type      396030 non-null  object
 24  mort_acc              358235 non-null  float64
 25  pub_rec_bankruptcies  395495 non-null  float64
 26  address               396030 non-null  object
dtypes: float64(12), object(15)
memory usage: 81.6+ MB